nginx:
 image: "registry.cn-hangzhou.aliyuncs.com/nginx-phpfpm/nginx-end"
 ports:
  - "8081:80"
 links:
  - "phpfpm"
 volumes:
  - ./:/var/www/html/
 container_name: marmot-application-nginx

phpfpm:
  image: "registry.cn-hangzhou.aliyuncs.com/phpfpm/phpfpm-end"
  volumes:
   - ./:/var/www/html/
  links:
   - "memcached-1"
   - "memcached-2"
   - "mysql"
  cap_add:
   - SYS_PTRACE
  environment:
   - APP_ENV=dev
  container_name: marmot-application-phpfpm

mysql:
  image: "registry.cn-hangzhou.aliyuncs.com/marmot/mysql-5.7"
  environment:
   - MYSQL_ROOT_PASSWORD=123456
  container_name: mysql

memcached-1:
  image: "registry.aliyuncs.com/marmot/memcached:1.0"
  container_name: marmot-application-memcached1

memcached-2:
  image: "registry.aliyuncs.com/marmot/memcached:1.0"
  container_name: marmot-application-memcached2
