<?php
/**
 * \d+(,\d+)*
 * 路由设置
 */
return [
    //user 用户
    //获取用户详情接口
    [
        'method'=>'GET',
        'rule'=>'/users/{id:\d+}',
        'controller'=>[
            'Marmot\Application\Member\Controller\UserController',
            'fetchOne'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/users/{ids:\d,[\d,]+}',
        'controller'=>[
            'Marmot\Application\Member\Controller\UserController',
            'fetchList'
        ]
    ],
    [
        'method'=>'GET',
        'rule'=>'/users',
        'controller'=>[
            'Marmot\Application\Member\Controller\UserController',
            'filter'
        ]
    ],
    //注册
    [
        'method'=>'POST',
        'rule'=>'/users',
        'controller'=>[
            'Marmot\Application\Member\Controller\UserController',
            'signUp'
        ]
    ],
    //登录
    [
        'method'=>'POST',
        'rule'=>'/users/signIn',
        'controller'=>[
            'Marmot\Application\Member\Controller\UserController',
            'signIn'
        ]
    ],
    //修改用户密码
    [
        'method'=>'PUT',
        'rule'=>'/users/{id:\d+}/updatePassword',
        'controller'=>[
            'Marmot\Application\Member\Controller\UserController',
            'updatePassword'
        ]
    ],
];
